- name: Create service group
  ansible.builtin.group:
    name: "{{ service_group }}"
    state: present
    gid: "{{ service_gid }}"
  become: true
  become_user: root

- name: Create service user
  ansible.builtin.user:
    name: "{{ service_user }}"
    group: "{{ service_group }}"
    shell: /bin/bash
    create_home: true
    home: "/home/{{ service_user }}"
    state: present
    uid: "{{ service_uid }}"
  become: true
  become_user: root

- name: Add ansible user to service group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ service_group }}"
    append: true
  become: true
  become_user: root
