networks:
  homeassistant_backend:
    driver: bridge
  swag_frontend:
    driver: bridge
  zigbee2mqtt_homeassistant:
    driver: bridge
  homeassistant_nut-upsd:
    driver: bridge
  openwrt:
    driver: bridge