services:
  nut-upsd:
    image: instantlinux/nut-upsd
    container_name: nut-upsd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - DRIVER=usbhid-ups
      - NAME=upsST625U
    devices:
      - /dev/bus/usb:/dev/bus/usb
    healthcheck:
      test: ['CMD', 'curl', 'host.docker.internal:3493']
    volumes:
      - "{{ nut_upsd_config_path }}:/config"
    restart: always
    networks:
      - homeassistant_nut-upsd