- name: create service group
  group:
    name: "{{ service_group }}"
    state: present
    gid: "{{ service_gid }}"
  become: true
  become_user: root

- name: create service user
  user:
    name: "{{ service_user }}"
    group: "{{ service_group }}"
    shell: /bin/bash
    create_home: true
    home: "/home/{{ service_user }}"
    state: present
    uid: "{{ service_uid }}"
  become: true
  become_user: root
