- name: Update apt
  ansible.builtin.apt:
    update_cache: yes
    upgrade: 'safe'
    state: latest

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname is defined

- name: Create users and groups
  ansible.builtin.include_tasks: configure_user_group.yml

- name: Configure patching
  ansible.builtin.include_tasks: configure_patching.yml

- name: Configure mounting points
  ansible.builtin.include_tasks: mount_disks.yml
