- name: ensure path exists
  file:
    name: "{{ homeassistant_config_path }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    recurse: true

- name: copy primary configuration
  template:
    src: "configuration.j2.yml"
    dest: "{{ homeassistant_config_path }}/configuration.yaml"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '664'
    backup: true
  notify: restart_homeassistant
