service_user: "docker"
service_group: "docker"
ansible_user: "ansible"
ansible_group: "ansible"

host_private_ip: "192.168.50.100"
homeassistant_port: 8123
homeassistant_subdomain: "ha"
swag_port: 443
swag_domain: "example.com"

debug: false
home_path: "/home/{{ service_user }}"
ansible_home_path: "/home/{{ ansible_user }}"
swag_config_path: "{{ home_path }}/swag/data"
homeassistant_config_path: "{{ home_path }}/homeassistant/data"
homeassistant_backup_disk_path: "{{ homeassistant_config_path }}/backup"
