services:
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=America/Los_Angeles
            - URL={{ swag_domain }}
            - VALIDATION=dns
            - SUBDOMAINS={{ homeassistant_subdomain }}
            - DNSPLUGIN=cloudflare
        volumes:
            - "{{ swag_config_path }}:/config"
        ports:
            - "{{ swag_port }}:{{ swag_port }}"
        restart: always
        healthcheck:
            test: ['CMD', 'curl', 'https://{{ homeassistant_subdomain }}.{{ swag_domain }}:{{ swag_port }}/manifest.json']
        networks:
            - swag_frontend
