services:
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=America/Los_Angeles
            - URL={{ swag_domain }}
            - VALIDATION=dns
            - SUBDOMAINS={{ homeassistant_subdomain }}
            - DNSPLUGIN=cloudflare
        volumes:
            - "{{ swag_config_path }}:/config"
        ports:
            - 443:443
        restart: always
        healthcheck:
          test: ['CMD', 'curl', '0.0.0.0:{{ swag_port }}']
