services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt
        restart: always
        volumes:
            - "{{ zigbee2mqtt_config_path }}:/config"
            - /run/udev:/run/udev:ro
        ports:
            - 8234:8080
        environment:
            - TZ=America/Los_Angeles
            - PUID=1001
            - PGID=1001
        devices:
            # - /dev/ttyUSB0:/dev/ttyUSB0
        networks:
            - zigbee2mqtt_homeassistant
        healthcheck:
            test: ['CMD', 'curl', '0.0.0.0:1883']