services:
    homeassistant:
        image: lscr.io/linuxserver/homeassistant
        container_name: homeassistant
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=America/Los_Angeles
            - DISABLE_JEMALLOC=true
        healthcheck:
          test: ['CMD', 'curl', '0.0.0.0:{{ homeassistant_port }}/manifest.json']
        volumes:
            - "{{ homeassistant_config_path }}:/config"
            - /run/dbus:/run/dbus:ro
        restart: always
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        ports:
            - "{{ homeassistant_port }}:{{ homeassistant_port }}"
            - 3493:3493 # Netwrok UPS Tools
