default_config:

logger:
  default: "{{ 'debug' if debug else 'info' }}"

automation: !include automations.yml
script: !include scripts.yml
scene: !include scenes.yml
group: !include groups.yml

python_script:

my:

http:
  server_port: {{ homeassistant_port }}
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.0/16  # Local Lan
    - 172.10.0.0/24  # Docker network
    - 172.0.0.1/32 # Localhost

mobile_app:
