default_config:

logger:
  default: info

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml

python_script:

my:

http:
  server_port: {{ homeassistant_port }}
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.0/16  # Local Lan
    - 172.0.0.0/8  # Docker network
    - 127.0.0.1/32 # Localhost

mobile_app:
