- name: Ensure config path exists
  ansible.builtin.file:
    name: "{{ mqtt_mount_path }}/config"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    recurse: true

- name: Ensure backup path exists
  ansible.builtin.file:
    dest: "{{ mqtt_backup_disk_path }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    recurse: true

- name: Apply mosquitto configuration
  ansible.builtin.template:
    src: mosquitto.conf.j2
    dest: "{{ mqtt_mount_path }}/config/mosquitto.conf"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: "0640"
  notify: Restart Mosquitto container
