- name: set fact incase force_container_recreate is not defined
  set_fact:
    force_container_recreate: 'false'
  when: force_container_recreate is not defined

- name: display force_container_recreate
  ansible.builtin.debug:
    msg: "force_container_recreate is set to {{ force_container_recreate }}"

- name: run general docker compose
  community.docker.docker_compose_v2:
    pull: always
    project_src: "{{ ansible_home_path }}/docker"
    assume_yes: true
    state: present
    build: always
    recreate: "{{ 'always' if force_container_recreate == 'true' else 'auto'}}"
    remove_orphans: true
