- name: set == 'true'
  set_fact:
    force_container_rebuild: 'false'
  when: force_container_rebuild is not defined

- name: debug force_container_rebuild
  debug:
    msg: "force_container_rebuild is set to {{ force_container_rebuild }} {{ 'always' if force_container_rebuild == 'true' else 'auto'}}"

- name: run general docker compose
  community.docker.docker_compose_v2:
    pull: always
    project_src: "{{ ansible_home_path }}/docker"
    assume_yes: true
    state: present
    build: always
    recreate: "{{ 'always' if force_container_rebuild == true else 'auto'}}"
    remove_orphans: true
