- name: ensure docker dir structure exists
  file:
    name: "{{ docker_compose_path }}/{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    recurse: true
  with_filetree: ../templates/docker
  when: item.state == 'directory'

- name: copy docker compose files
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_path }}/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
  with_filetree: ../templates/docker
  when: item.state == 'file'
  
