- name: Ensure docker dir structure exists
  ansible.builtin.file:
    name: "{{ docker_compose_path }}/{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
    recurse: true
  with_filetree: ../templates/docker
  when: item.state == 'directory'

- name: Copy docker compose files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_path }}/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
  with_filetree: ../templates/docker
  when: item.state == 'file'
