- name: copy docker compose directory
  template:
    src: "{{ item }}"
    dest: "{{ ansible_home_path }}/docker/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
  with_fileglob:
    - ../templates/docker/**.yml
  become: true
  become_user: root
