- name: copy docker compose directory
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_home_path }}/docker/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
  with_filetree: ../templates/docker
  when: item.state == 'file'
