- name: check if docker is installed
  command: docker --version
  register: docker_version
  ignore_errors: true

- name: install docker script
  shell: "sudo curl -sSL https://get.docker.com | sh"
  become: true
  become_user: "{{ ansible_user }}"
  when: docker_version.rc != 0

- name: configure docker service
  service:
    name: docker
    enabled: true
    state: started

- name: configure docker
  include_tasks: "configure_docker.yml"
