- name: install docker script
  shell: "sudo curl -sSL https://get.docker.com | sh"
  become: true
  become_user: "{{ ansible_user }}"

- name: configure docker service
  service:
    name: docker
    enabled: true
    state: started

- name: configure docker
  include_tasks: "configure_docker.yml"
