- name: install docker script
  shell: "curl -sSL https://get.docker.com | sh"

- name: configure docker service
  service:
    name: docker
    enabled: true
    state: started

- name: configure docker
  include_tasks: "configure_docker.yml"
