- name: run general docker compose
  community.docker.docker_compose_v2:
    pull: always
    project_src: "{{ ansible_home_path }}/docker"
    assume_yes: true
    state: present
    build: always
    recreate: "{{ 'always' if force_container_rebuild is defined and force_container_rebuild else 'auto'}}"
