---
- name: Configure base host
  hosts: all
  roles:
    - base
    - base-tailscale
    - base-upsd
    - base-docker
  become: true
  become_user: root

- name: Apply docker compose
  hosts: all
  roles:
    - docker-compose
  become: true
  become_user: root

- name: Apply docker container configurations
  hosts: all
  roles:
    - config-homeassistant
    - config-mosquitto
    - config-swag
  become: true
  become_user: root
