---
- name: Complete setup and configuration
  hosts: all
  roles:
    - common
    - nut_upsd
    - docker
    - mosquitto
    - homeassistant
    - docker-wol
    - swag
  become: true
  become_user: root
