- name: Restart nut-server and nut-client
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nut-server
    - nut-client
  become: true
  become_user: root
  listen: restart_nut_upsd
