- name: ensure path exists
  file:
    name: "{{ swag_config_path }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    recurse: true

- name: configure swag ha subdomain
  template:
    src: "nginx/proxy-confs/homeassistant.subdomain.j2.conf"
    dest: "{{ swag_config_path }}/nginx/proxy-confs/homeassistant.subdomain.conf"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0644'
