- name: ensure path exists
  file:
    name: "{{ swag_config_path }}/nginx/proxy-confs"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    recurse: true

- name: configure swag ha subdomain
  template:
    src: "nginx/proxy-confs/homeassisant.subdomain.j2.conf"
    dest: "{{ swag_config_path }}/nginx/proxy-confs/homeassisant.subdomain.conf"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0644'
    backup: true
  notify: restart_swag
